# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('dept_id', models.IntegerField()),
                ('it_name', models.CharField(max_length=50)),
                ('it_f', models.DateField()),
                ('it_t', models.DateField()),
                ('emp_id', models.CharField(max_length=5)),
                ('high_qual', models.CharField(max_length=50)),
                ('doj', models.DateField()),
                ('Present_pos', models.CharField(max_length=50)),
                ('Held_from', models.DateField()),
                ('exp_teach', models.IntegerField()),
                ('exp_res', models.IntegerField()),
                ('exp_indus', models.IntegerField()),
            ],
        ),
    ]
