# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='Held_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='Present_pos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='exp_indus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='exp_res',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='exp_teach',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='high_qual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='it_f',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='it_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empdetail',
            name='it_t',
            field=models.DateField(null=True),
        ),
    ]
