# Generated by Django 2.0.2 on 2019-08-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_indus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_res',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_teach',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
