# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0002_auto_20180902_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='doj',
            field=models.DateField(null=True),
        ),
    ]
