# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-04 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0003_auto_20180904_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deptartment',
            new_name='department',
        ),
    ]
