# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0003_auto_20180902_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='dept_id',
            field=models.CharField(max_length=5),
        ),
    ]
