# Generated by Django 2.0.2 on 2019-08-21 04:42

from django.db import migrations, models
import facform1.formatChecker


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0003_auto_20190820_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetailform',
            old_name='internship_report_file',
            new_name='internship_report_file1',
        ),
        migrations.AddField(
            model_name='empdetailform',
            name='internship_report_file3',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[facform1.formatChecker.validate_file_size]),
        ),
    ]
