# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-06 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0004_auto_20180904_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t4_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_pass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t4_stu_perpass',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_f1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_f2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_favg',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_2_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_ai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_ci',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_cn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_i',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_nm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='c_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='c_index',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='c_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='c_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='c_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_f',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_s',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_f',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_s',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_c',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_f',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_s',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_index',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_issn',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='j_volume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='onl_course_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='p_i_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='p_n_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='p_s_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='w_i_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='w_n_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='w_s_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='hod_marks1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='hod_marks2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='prin_marks1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='prin_marks2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='ta_dr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='ta_hod_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='ta_ic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='ta_ir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='ta_prin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='tot_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
