# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0005_auto_20180902_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='empDetailForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=50, null=True)),
                ('it_f', models.DateField(null=True)),
                ('it_t', models.DateField(null=True)),
                ('high_qual', models.CharField(max_length=50, null=True)),
                ('doj', models.DateField(null=True)),
                ('Present_pos', models.CharField(max_length=50, null=True)),
                ('Held_from', models.DateField(null=True)),
                ('exp_teach', models.IntegerField(null=True)),
                ('exp_res', models.IntegerField(null=True)),
                ('exp_indus', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='Held_from',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='Present_pos',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='exp_indus',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='exp_res',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='exp_teach',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='high_qual',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='it_f',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='it_name',
        ),
        migrations.RemoveField(
            model_name='empdetail',
            name='it_t',
        ),
    ]
