# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-06 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0006_auto_20180906_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetailform',
            old_name='emp_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='feedbacktab',
            old_name='emp_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='emp_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='remarks',
            old_name='emp_id',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_id',
        ),
    ]
