# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0007_feedbacktab'),
    ]

    operations = [
        migrations.CreateModel(
            name='rd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_s_d', models.IntegerField()),
                ('w_n_d', models.IntegerField()),
                ('w_i_d', models.IntegerField()),
                ('p_s_d', models.IntegerField()),
                ('p_n_d', models.IntegerField()),
                ('p_i_d', models.IntegerField()),
                ('onl_course_c', models.IntegerField()),
                ('j_index', models.CharField(max_length=30)),
                ('j_name', models.CharField(max_length=30)),
                ('j_title', models.CharField(max_length=30)),
                ('j_volume', models.CharField(max_length=30)),
                ('j_issn', models.CharField(max_length=30)),
                ('j_date', models.DateField()),
                ('j_page', models.IntegerField()),
                ('c_name', models.CharField(max_length=30)),
                ('c_title', models.CharField(max_length=30)),
                ('c_place', models.CharField(max_length=30)),
                ('c_date', models.DateField()),
                ('c_index', models.CharField(max_length=30)),
                ('book_i', models.IntegerField()),
                ('book_n', models.IntegerField()),
                ('book_ci', models.IntegerField()),
                ('book_cn', models.IntegerField()),
                ('book_ai', models.IntegerField()),
                ('book_nm', models.IntegerField()),
                ('if_s', models.CharField(max_length=30)),
                ('if_f', models.CharField(max_length=30)),
                ('if_c', models.CharField(max_length=30)),
                ('ef_s', models.CharField(max_length=30)),
                ('ef_f', models.CharField(max_length=30)),
                ('ef_c', models.CharField(max_length=30)),
                ('eef_s', models.CharField(max_length=30)),
                ('eef_f', models.CharField(max_length=30)),
                ('eef_c', models.CharField(max_length=30)),
                ('Cw_2', models.CharField(max_length=30)),
                ('Cw_2_5', models.CharField(max_length=30)),
                ('Cw_5', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='remarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_ir', models.TextField()),
                ('ta_ic', models.TextField()),
                ('ta_dr', models.TextField()),
                ('hod_marks1', models.IntegerField()),
                ('hod_marks2', models.IntegerField()),
                ('ta_hod_remarks', models.TextField()),
                ('ta_prin_remarks', models.TextField()),
                ('prin_marks1', models.IntegerField()),
                ('prin_marks2', models.IntegerField()),
                ('tot_marks', models.IntegerField()),
            ],
        ),
    ]
