# Generated by Django 2.0.2 on 2018-09-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0007_auto_20180906_0541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empdetailform',
            old_name='username',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='feedbacktab',
            old_name='username',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='username',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='remarks',
            old_name='username',
            new_name='info',
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
