# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0008_rd_remarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='empDetail',
        ),
    ]
