# Generated by Django 2.0.2 on 2018-09-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0008_auto_20180906_1313'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='user',
            name='teach_status',
            field=models.BooleanField(default=False),
        ),
    ]
