# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0009_delete_empdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='empDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('dept_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
