# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-02 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0010_empdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetail',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
