# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-16 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0010_auto_20180915_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='remarks1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_marks1', models.IntegerField(blank=True, null=True)),
                ('hod_marks2', models.IntegerField(blank=True, null=True)),
                ('ta_hod_remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='remarks2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_prin_remarks', models.TextField(blank=True, null=True)),
                ('prin_marks1', models.IntegerField(blank=True, null=True)),
                ('prin_marks2', models.IntegerField(blank=True, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.Department')),
            ],
        ),
        
        migrations.RemoveField(
            model_name='remarks',
            name='prin_marks1',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='prin_marks2',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='principal_status',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='ta_hod_remarks',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='ta_prin_remarks',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='total_marks',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='remarks2',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remarks1',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
