# Generated by Django 2.0.2 on 2018-09-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0010_auto_20180915_1141'),
    ]

    operations = [
        
    ]
