# Generated by Django 2.0.2 on 2018-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0011_remove_empdetailform_present_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rd',
            old_name='c_c_index',
            new_name='f_c_m',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_c_name',
            new_name='f_j_m',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_c_date',
            new_name='o_c_date',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_c_place',
            new_name='o_c_index',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_c_title',
            new_name='o_c_m',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_index',
            new_name='o_c_name',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_issn',
            new_name='o_c_place',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_name',
            new_name='o_c_title',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_date',
            new_name='o_j_date',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_title',
            new_name='o_j_index',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_volume',
            new_name='o_j_issn',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_m',
            new_name='o_j_m',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='j_m',
            new_name='o_j_name',
        ),
        migrations.RenameField(
            model_name='rd',
            old_name='c_j_page',
            new_name='o_j_page',
        ),
        migrations.AddField(
            model_name='rd',
            name='o_j_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='o_j_volume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='s_c_m',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='s_j_m',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
