# Generated by Django 2.0.2 on 2018-09-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0012_auto_20180916_1717'),
    ]

    operations = [
        
    ]
