# Generated by Django 2.0.2 on 2018-09-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0013_auto_20180916_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacktab',
            old_name='o_t4_stu_perpass',
            new_name='o_l4_stu_perpass',
        ),
    ]
