# Generated by Django 2.0.2 on 2018-09-16 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0011_auto_20180916_1752'),
        ('facform1', '0014_auto_20180916_1828'),
    ]

    operations = [
    ]
