# Generated by Django 2.0.2 on 2018-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0015_merge_20180916_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetailform',
            name='Present_pos',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='hod_marks1',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='hod_marks2',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='hod_status',
        ),
        migrations.RemoveField(
            model_name='remarks',
            name='teach_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dept_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
