# Generated by Django 2.0.2 on 2018-09-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0018_auto_20180917_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd',
            name='doc_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
