# Generated by Django 2.0.2 on 2018-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0020_auto_20180917_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd',
            name='doc_link',
        ),
        migrations.AddField(
            model_name='user',
            name='doc_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
