# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0022_auto_20180917_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd',
            name='department',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='designation',
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_info',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='remarks2',
            name='prin_marks3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remarks2',
            name='ta_prin_remarks1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='doc_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
