# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0023_auto_20180918_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipr_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rd',
            name='ipr_info',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='ipr_status',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='ipr_type',
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.ipr'),
        ),
    ]
