# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0024_auto_20180919_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd',
            name='ipr',
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='ipr_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='ipr',
        ),
    ]
