# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0025_auto_20180919_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipr_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipr', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ipr_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipr', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rd',
            name='ipr_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.ipr_status'),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ipr_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.ipr_type'),
        ),
    ]
