# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0027_auto_20180919_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipr_status',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ipr_type',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
