# Generated by Django 2.0.2 on 2018-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0028_auto_20180919_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks2',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
