# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0029_auto_20180920_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rd',
            name='ipr_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.ipr_status'),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ipr_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.ipr_type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
