# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0031_auto_20180921_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(blank=True, max_length=100, null=True)),
                ('c_title', models.CharField(blank=True, max_length=100, null=True)),
                ('c_place', models.CharField(blank=True, max_length=100, null=True)),
                ('c_date', models.DateField(blank=True, null=True)),
                ('c_index', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.author')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_index', models.CharField(blank=True, max_length=100, null=True)),
                ('j_name', models.CharField(blank=True, max_length=100, null=True)),
                ('j_title', models.CharField(blank=True, max_length=100, null=True)),
                ('j_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('j_issn', models.CharField(blank=True, max_length=100, null=True)),
                ('j_date', models.DateField(blank=True, null=True)),
                ('j_page', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facform1.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_c_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_c_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_c_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_c_place',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_c_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_issn',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_page',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='f_j_volume',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_c_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_c_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_c_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_c_place',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_c_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_issn',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_page',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='o_j_volume',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_c_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_c_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_c_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_c_place',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_c_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_date',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_index',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_issn',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_name',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_page',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_title',
        ),
        migrations.RemoveField(
            model_name='rd',
            name='s_j_volume',
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p10_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p10_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p10_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p10_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p3_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p3_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p3_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p4_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p4_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p4_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p5_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p5_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p5_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p6_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p6_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p6_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p7_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p7_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p7_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p7_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p8_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p8_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p8_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p8_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p9_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p9_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p9_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedbacktab',
            name='p9_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l1_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l2_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l3_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l4_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l5_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l_f_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_l_r_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_o_f_r_final',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t1_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t2_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t3_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t_f_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='e_t_r_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l1_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l2_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l3_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l4_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l5_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l_f_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_l_r_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t1_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t2_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t3_stu_perpass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t_f_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='o_t_r_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_f1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_f2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_favg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacktab',
            name='p_f_avg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_2_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='Cw_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='book_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='eef_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='ef_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='f_c_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='f_j_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_f',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='if_s',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='o_c_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='o_j_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='onl_course_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='p_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='rd_tot_marks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='rp_marks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='s_c_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='s_j_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rd',
            name='w_m',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='journal',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
