# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0032_auto_20180922_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd',
            name='f_c_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='f_j_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='o_c_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='o_j_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='s_c_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='s_j_n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
