# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0033_auto_20180922_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='c_index',
            new_name='c1_author',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='c_date',
            new_name='c1_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='c_name',
            new_name='c1_index',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='c_place',
            new_name='c1_name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='c_title',
            new_name='c1_place',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_date',
            new_name='j1_date',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_index',
            new_name='j1_index',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_issn',
            new_name='j1_issn',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_name',
            new_name='j1_name',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_page',
            new_name='j1_page',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_title',
            new_name='j1_title',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='j_volume',
            new_name='j1_volume',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
        migrations.AddField(
            model_name='conference',
            name='c1_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c4_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c5_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c6_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c7_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='c8_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j2_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j3_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j4_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j5_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j6_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j7_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_issn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='j8_volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='author',
        ),
    ]
