# Generated by Django 2.0.2 on 2018-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0037_auto_20180922_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_indus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_res',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empdetailform',
            name='exp_teach',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
