# Generated by Django 2.0.2 on 2018-09-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0038_auto_20180923_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='doc_link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
