# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-18 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0041_auto_20181218_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdetailform',
            name='internship_report_file',
        ),
    ]
