# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facform1', '0042_remove_empdetailform_internship_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetailform',
            name='internship_report_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
